baseURL = "https://affectionate-hermann-938e8c.netlify.com/"
languageCode = "en-us"
title = "Joël's Blog"
theme = "coder"

[params] # theme parameters
    author = "Joël Weber" # author's name
    info = "Computerexpert" # author's job title or info
    description = "Joël zijn persoonlijke website" # site description
    keywords = "blog,developer,personal" # site keywords

    # wether you want to hide copyright and credits in the footer
    hideCredits = false
    hideCopyright = false

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/jlwbr"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/jlwbr"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Over"
    weight = 2
    url = "/over/"
